CONN system/admin
GRANT CREATE VIEW TO kifi;

CREATE OR REPLACE VIEW MYBOARDLIST
AS
	SELECT MB.MB_NUM,MB.MB_TITLE,MB.MB_CONTENT,MB.MB_DATE,MB.MB_VIEWS,AA.COMMENT_CNT,BB.LIKE_CNT,MP.MP_NUM,MP.MP_SAVIMG,MV.MV_NUM,MV.MV_SAVVID
	FROM MY_BOARD MB,
	(
	    SELECT NVL(COUNT(MYC_NUM),0) COMMENT_CNT,MC.MB_NUM
	    FROM MY_COMMENT MC,MY_BOARD MBB
	    WHERE MC.MB_NUM=MBB.MB_NUM
	    GROUP BY MC.MB_NUM
	)AA,
	(
		SELECT NVL(COUNT(MBL_NUM),0) LIKE_CNT,MBL.MB_NUM
		FROM MY_BOARD_LIKE MBL,MY_BOARD MBBB
		WHERE MBL.MB_NUM=MBBB.MB_NUM
		GROUP BY MBL.MB_NUM
	)BB,
	(
		SELECT MB_NUM,MP_NUM,MP_SAVIMG
		FROM MY_PHOTO
		WHERE ROWID IN 
			(
				SELECT MAX(ROWID) FROM MY_PHOTO GROUP BY MB_NUM
			)
	)MP,
	(
		SELECT MB_NUM,MV_NUM,MV_SAVVID
		FROM MY_VIDEO
		WHERE ROWID IN 
			(
				SELECT MAX(ROWID) FROM MY_VIDEO GROUP BY MB_NUM
			)	
	)MV
	WHERE MP.MB_NUM(+)=MB.MB_NUM AND MV.MB_NUM(+)=MB.MB_NUM AND AA.MB_NUM(+)=MB.MB_NUM AND BB.MB_NUM(+)=MB.MB_NUM;
	