-- Tag관련

--SELECT T.TAG_NUM,T.TAG_NAME,MT.MB_NUM
--FROM TAG T,MY_TAG MT
--WHERE MT.TAG_NUM(+)=T.TAG_NUM;

--SELECT T.TAG_NUM,T.TAG_NAME,MT.MB_NUM,CT.CB_NUM
--FROM TAG T,MY_TAG MT,COMM_TAG CT
--WHERE MT.TAG_NUM(+)=T.TAG_NUM AND CT.TAG_NUM(+)=T.TAG_NUM;

--SELECT T.TAG_NAME,COUNT(T.TAG_NAME)
--FROM TAG T,MY_TAG MT,COMM_TAG CT
--WHERE MT.TAG_NUM(+)=T.TAG_NUM AND CT.TAG_NUM(+)=T.TAG_NUM
--GROUP BY T.TAG_NAME;

SELECT T.TAG_NUM,T.TAG_NAME,AA.TAG_CNT,MT.MB_NUM
FROM TAG T,MY_TAG MT,
(
    SELECT TT.TAG_NAME,COUNT(TT.TAG_NAME) TAG_CNT
    FROM TAG TT,MY_TAG MT,COMM_TAG CT
    WHERE MT.TAG_NUM(+)=TT.TAG_NUM AND CT.TAG_NUM(+)=TT.TAG_NUM
    GROUP BY TT.TAG_NAME
)AA
WHERE MT.TAG_NUM(+)=T.TAG_NUM AND AA.TAG_NAME=T.TAG_NAME AND MT.MB_NUM=1;


-- boardlistview에 taglist 반영시킨거...넘 복작복작해지는데 이거 쓸지 말지 고민중(이거 쓰려면 mybatis-resultMap 써야됨)
    SELECT MB.MB_NUM,MB.USER_NUM,MEM.USER_ID,MEM.USER_NICKNAME,MEM.USER_EMAIL,MB.MB_TITLE,MB.MB_CONTENT,MB.MB_DATE,MB.MB_VIEWS,
    AA.COMMENT_CNT,BB.LIKE_CNT,MP.MP_NUM,MP.MP_SAVIMG,MV.MV_NUM,MV.MV_SAVVID,MSP.MSP_SAVIMG,
    TAGLIST.TAG_NUM,TAGLIST.TAG_NAME,TAGLIST.TAG_CNT
	FROM MY_BOARD MB,MEMBERS MEM,
	(
	    SELECT NVL(COUNT(MYC_NUM),0) COMMENT_CNT,MC.MB_NUM
	    FROM MY_COMMENT MC,MY_BOARD MBB
	    WHERE MC.MB_NUM=MBB.MB_NUM
	    GROUP BY MC.MB_NUM
	)AA,
	(
		SELECT NVL(COUNT(MBL_NUM),0) LIKE_CNT,MBL.MB_NUM
		FROM MY_BOARD_LIKE MBL,MY_BOARD MBBB
		WHERE MBL.MB_NUM=MBBB.MB_NUM
		GROUP BY MBL.MB_NUM
	)BB,
	(
		SELECT MB_NUM,MP_NUM,MP_SAVIMG
		FROM MY_PHOTO
		WHERE ROWID IN 
			(
				SELECT MAX(ROWID) FROM MY_PHOTO GROUP BY MB_NUM
			)
	)MP,
	(
		SELECT MB_NUM,MV_NUM,MV_SAVVID
		FROM MY_VIDEO
		WHERE ROWID IN 
			(
				SELECT MAX(ROWID) FROM MY_VIDEO GROUP BY MB_NUM
			)	
	)MV,
    MY_SKIN MS,MY_SKIN_PROFILE MSP,
    (
        SELECT T.TAG_NUM,T.TAG_NAME,AA.TAG_CNT,MT.MB_NUM
        FROM TAG T,MY_TAG MT,
        (
            SELECT TT.TAG_NAME,COUNT(TT.TAG_NAME) TAG_CNT
            FROM TAG TT,MY_TAG MT,COMM_TAG CT
            WHERE MT.TAG_NUM(+)=TT.TAG_NUM AND CT.TAG_NUM(+)=TT.TAG_NUM
            GROUP BY TT.TAG_NAME
        )AA
        WHERE MT.TAG_NUM(+)=T.TAG_NUM AND AA.TAG_NAME=T.TAG_NAME
    )TAGLIST
	WHERE MP.MB_NUM(+)=MB.MB_NUM AND MV.MB_NUM(+)=MB.MB_NUM AND AA.MB_NUM(+)=MB.MB_NUM AND BB.MB_NUM(+)=MB.MB_NUM AND MB.USER_NUM=MEM.USER_NUM 
    AND MEM.USER_NUM=MS.USER_NUM AND MS.MS_NUM=MSP.MS_NUM AND MS.MS_USING=1 AND TAGLIST.MB_NUM=MB.MB_NUM;
    
-- VOTELISTVIEW + VOTING_OPTION -> VOTE게시판 LIST에 사용
SELECT CL.VOTE_NUM,CL.COMM_NUM,CL.VOTE_TITLE,CL.REMAIN,CL.USER_NICKNAME,CL.USER_EMAIL,CL.MSP_SAVIMG,CL.CNT,
VO.OPTION_NUM,VO.VO_CONTENT
FROM COMMVOTELIST CL,VOTING_OPTION VO
WHERE CL.VOTE_NUM=VO.VOTE_NUM AND CL.COMM_NUM=1
ORDER BY VOTE_NUM DESC,OPTION_NUM ASC;