CREATE OR REPLACE VIEW MYBOARDLIST
AS	
    SELECT MB.MB_NUM,MB.USER_NUM,MEM.USER_ID,MEM.USER_NICKNAME,MEM.USER_EMAIL,MB.MB_TITLE,MB.MB_CONTENT,MB.MB_DATE,MB.MB_VIEWS,
    AA.COMMENT_CNT,BB.LIKE_CNT,MP.MP_NUM,MP.MP_SAVIMG,MV.MV_NUM,MV.MV_SAVVID,MSP.MSP_SAVIMG
	FROM MY_BOARD MB,MEMBERS MEM,
	(
	    SELECT NVL(COUNT(MYC_NUM),0) COMMENT_CNT,MC.MB_NUM
	    FROM MY_COMMENT MC,MY_BOARD MBB
	    WHERE MC.MB_NUM=MBB.MB_NUM
	    GROUP BY MC.MB_NUM
	)AA,
	(
		SELECT NVL(COUNT(MBL_NUM),0) LIKE_CNT,MBL.MB_NUM
		FROM MY_BOARD_LIKE MBL,MY_BOARD MBBB
		WHERE MBL.MB_NUM=MBBB.MB_NUM
		GROUP BY MBL.MB_NUM
	)BB,
	(
		SELECT MB_NUM,MP_NUM,MP_SAVIMG
		FROM MY_PHOTO
		WHERE ROWID IN 
			(
				SELECT MAX(ROWID) FROM MY_PHOTO GROUP BY MB_NUM
			)
	)MP,
	(
		SELECT MB_NUM,MV_NUM,MV_SAVVID
		FROM MY_VIDEO
		WHERE ROWID IN 
			(
				SELECT MAX(ROWID) FROM MY_VIDEO GROUP BY MB_NUM
			)	
	)MV,
    MY_SKIN MS,MY_SKIN_PROFILE MSP
	WHERE MP.MB_NUM(+)=MB.MB_NUM AND MV.MB_NUM(+)=MB.MB_NUM AND AA.MB_NUM(+)=MB.MB_NUM AND BB.MB_NUM(+)=MB.MB_NUM AND MB.USER_NUM=MEM.USER_NUM 
    AND MEM.USER_NUM=MS.USER_NUM AND MS.MS_NUM=MSP.MS_NUM AND MS.MS_USING=1;
    
CREATE OR REPLACE VIEW MYCOMMENTLIST
AS
    SELECT MC.*,AA.CNT,M.USER_ID,MSP.MSP_SAVIMG
    FROM MY_COMMENT MC,MEMBERS M,MY_SKIN MS,MY_SKIN_PROFILE MSP,
    (
        SELECT NVL(COUNT(MCL_NUM),0) CNT,MYC_NUM
        FROM MY_COMMENT_LIKE
        GROUP BY MYC_NUM
    )AA
    WHERE AA.MYC_NUM(+)=MC.MYC_NUM AND M.USER_NUM=MC.USER_NUM AND M.USER_NUM=MS.USER_NUM AND MS.MS_NUM=MSP.MS_NUM AND MS.MS_USING=1
    ORDER BY MC.MYC_NUM DESC;
    
CREATE OR REPLACE VIEW MYBOARDLIKELIST
AS
	SELECT MBL.MBL_NUM,MBL.MB_NUM,MBL.USER_NUM,MEM.USER_ID,MEM.USER_NICKNAME,MEM.USER_EMAIL,MSP.MSP_SAVIMG
	FROM MY_BOARD_LIKE MBL,MEMBERS MEM,MY_SKIN MS,MY_SKIN_PROFILE MSP
	WHERE MBL.USER_NUM=MEM.USER_NUM AND MEM.USER_NUM=MS.USER_NUM AND MS.MS_NUM=MSP.MS_NUM AND MS.MS_USING=1;



	