--------------------------------------------------------
--  파일이 생성됨 - 화요일-11월-06-2018   
--------------------------------------------------------
DROP TABLE "KFI"."AB_PHOTO" cascade constraints;
DROP TABLE "KFI"."ACCUSE" cascade constraints;
DROP TABLE "KFI"."ADMIN" cascade constraints;
DROP TABLE "KFI"."ADMIN_BOARD" cascade constraints;
DROP TABLE "KFI"."CERTI_MEMBERS" cascade constraints;
DROP TABLE "KFI"."COMM_BOARD" cascade constraints;
DROP TABLE "KFI"."COMM_BOARD_LIKE" cascade constraints;
DROP TABLE "KFI"."COMM_CALENDAR" cascade constraints;
DROP TABLE "KFI"."COMM_CHAT" cascade constraints;
DROP TABLE "KFI"."COMM_COMMENT" cascade constraints;
DROP TABLE "KFI"."COMM_COMMENT_LIKE" cascade constraints;
DROP TABLE "KFI"."COMM_GATHERING" cascade constraints;
DROP TABLE "KFI"."COMM_PHOTO" cascade constraints;
DROP TABLE "KFI"."COMM_REFUSE" cascade constraints;
DROP TABLE "KFI"."COMM_SKIN" cascade constraints;
DROP TABLE "KFI"."COMM_SKIN_COVER" cascade constraints;
DROP TABLE "KFI"."COMM_SKIN_PROFILE" cascade constraints;
DROP TABLE "KFI"."COMM_TAG" cascade constraints;
DROP TABLE "KFI"."COMM_USER_LIST" cascade constraints;
DROP TABLE "KFI"."COMM_VIDEO" cascade constraints;
DROP TABLE "KFI"."COMM_VOTE" cascade constraints;
DROP TABLE "KFI"."COMMUNITY" cascade constraints;
DROP TABLE "KFI"."FAQ" cascade constraints;
DROP TABLE "KFI"."FRIENDS" cascade constraints;
DROP TABLE "KFI"."MEMBERS" cascade constraints;
DROP TABLE "KFI"."MY_BOARD" cascade constraints;
DROP TABLE "KFI"."MY_BOARD_LIKE" cascade constraints;
DROP TABLE "KFI"."MY_CHAT" cascade constraints;
DROP TABLE "KFI"."MY_COMMENT" cascade constraints;
DROP TABLE "KFI"."MY_COMMENT_LIKE" cascade constraints;
DROP TABLE "KFI"."MY_PHOTO" cascade constraints;
DROP TABLE "KFI"."MY_SKIN" cascade constraints;
DROP TABLE "KFI"."MY_SKIN_COVER" cascade constraints;
DROP TABLE "KFI"."MY_SKIN_PROFILE" cascade constraints;
DROP TABLE "KFI"."MY_TAG" cascade constraints;
DROP TABLE "KFI"."MY_VIDEO" cascade constraints;
DROP TABLE "KFI"."TAG" cascade constraints;
DROP TABLE "KFI"."VOTEING_USERLIST" cascade constraints;
DROP TABLE "KFI"."VOTING_OPTION" cascade constraints;

