CONN system/admin
GRANT CREATE VIEW TO kifi;

CREATE OR REPLACE VIEW MYBOARDLIST
AS
	SELECT MB.MB_NUM,MB.MB_TITLE,MB.MB_CONTENT,MB.MB_DATE,MB.MB_VIEWS,MP.MP_NUM,MP.MP_SAVIMG,MV.MV_NUM,MV.MV_SAVVID
	FROM MY_BOARD MB,MY_PHOTO MP,MY_VIDEO MV
	WHERE MP.MB_NUM(+)=MB.MB_NUM AND MV.MB_NUM(+)=MB.MB_NUM;